### ISSUE TITLE
TP3: Conflitos entre peças e estruturas de apoio

### ISSUE THREAD

**Issue by Bragado** [Bragado/LAIG#1]
As peças são do mesmo tamanho que as estruturas onde estão colocadas criando um mau aspeto
Solução: diminuir ligeiramente o tamanho das estruturas

**Comment by PedroMiguelGomes** [comment]
Aqui devo diminuir o tamanho das esruturas (tabuleiro/escadas) ou aumentar um pouco? E que como as pecas so tem texturas em cima nao sei o que ficaria melhor
